### ISSUE TITLE
Email Notification Templates

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#110]
Need some email templates created.  For now they can be simple but should convey basic info. Follow the mjml example in the Harvest.Email lib and the homeController.  If you have some good thoughts about how to create a shared header/body for the emails that'd be nice too.  Payments emails might be a good example if looking for styles

Farm Manager:
* [x] 1. New request comes in
* [x] 2. Quote is accepted
* [x] 3. Quote is rejected
* [x] 4. Change request is created

Professor:
* [x] 1. Quote ready for approval

**Comment by jSylvestre** [comment]
Don't forget to use mailtrap. Much easier to check against

**Comment by jSylvestre** [comment]
This is the current shared header:
https://github.com/ucdavis/Harvest/blob/main/Harvest.Email/Views/Shared/_EmailLayout_mjml.cshtml
