### ISSUE TITLE
Create approved flag in Projects table

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#112]
Discussion: How should we handle change requests?  I'm thinking the simplest thing is to add a field to the projects table for like ChangeRequest (TXT) where they describe what they want changed, and we also update the status to something like `ChangeRequested` to indicate the difference.  Then when a new change quote is submitted, we go back to `PendingQuoteApproval` status.  The downside is that we want to keep taking expenses the whole time, and the quote might never be approved.  So I'm thinking the simplest thing is to add an `Approved` flag which when true means that it's a valid project that can take expenses.  We would still need to determine how to handle proposed accounts though. Perhaps we can do something clever with merging multiple projects (as in, should the change request be a separate project which merges back to the main one once accepted?)

**Comment by jSylvestre** [comment]
So not just for changing accounts, but other project settings as well?
If so, then the new quote can't change anything until it is approved.

**Comment by srkirkland** [comment]
Yea, though changing accounts is it's own issue that we'll have to address, since changing an account shouldn't really require a new quote
