### ISSUE TITLE
Do we want a db table for emails?

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Harvest#120]
Then a job can send them, check for errors, and mark as sent. It would just have a few fields:
email, subject, body, text body, (maybe projectId), sent date, status.

I don't really see a good way to do digest emails at the moment.

**Comment by srkirkland** [comment]
I think this is another one of those we probably will once we get to it things.  Nobody has said they want digests yet and thus at this point focusing on just sending emails and getting fancy later is my plan
