### ISSUE TITLE
Remind Cal how to use fontawesome in react

### ISSUE THREAD

**Issue by cydoval** [ucdavis/Harvest#155]

**Comment by srkirkland** [comment]
@cydoval For now, just import the icons individually -- once we figure out all the ones we want we can start to build up a library.  So for example, in some component you can do 

```
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'
```

and then when you need to use it do `<FontAwesomeIcon icon={faCoffee} />`
