### ISSUE TITLE
Acreage Expense 

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Harvest#181]
When creating the Acreage expense, check if the amount being created is zero and exit early.
There can be an acreage of zero, so this will happen.

**Comment by sprucely** [comment]
@jSylvestre I was about to fix the acreage expense calculation while working on #170. Should I leave that to be addressed in this issue?

**Comment by jSylvestre** [comment]
> @jSylvestre I was about to fix the acreage expense calculation while working on #170. Should I leave that to be addressed in this issue?

@sprucely 👍
