### ISSUE TITLE
Prettify unit display on invoice

### ISSUE THREAD

**Issue by sprucely** [ucdavis/Harvest#203]
It's still only in my branch swe/FixInvoice. Feel free to commit and push directly to it.

https://github.com/ucdavis/Harvest/blob/48cb31d4e59193cee3c27d27b1a08afb2db4f4cb/Harvest.Web/ClientApp/src/Expenses/ExpenseDisplay.tsx#L30

![image](https://user-images.githubusercontent.com/2398955/120564180-39c03600-c3bf-11eb-8d25-48bc1d5a0c25.png)

**Comment by sprucely** [comment]
It's now in main branch.

**Comment by cydoval** [comment]
I'm addressing this in my sitecleanup branch, its just a css change
