### ISSUE TITLE
Attach files to project request and project itself after creation

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#212]
Can be done by PI or sup or FM.

Should show on project details header.

- [x] Add files to request creation page
- [x] Add files from project details page
- [x] Allow removing unwanted files? If so, it should delete blob files too.
- [x] Show files on project details page

**Comment by jSylvestre** [comment]
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.blobs-readme?view=azure-dotnet  ???
The processes Payments uses have been deprecated

**Comment by jSylvestre** [comment]
SAS? 
https://docs.microsoft.com/en-us/azure/storage/common/storage-sas-overview

**Comment by srkirkland** [comment]
looks like we are done with this one
