### ISSUE TITLE
Task/Ticketing system

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#223]
Ability for PIs (and their staff?) to be able to create work tickets associated with a project.  Simple requirements text, date due, completed flag (default to false).  Perhaps we allow some small back and forth with task comments similar to service now.  At some point the task is marked as completed.

Open tasks should show on the project details page, there should be a list of all tasks, and it would be a bonus if closed tasks were linked to the next invoice generated after they were closed.

From Brad:
> We talked about the “ticketing” system Israel mentioned.  Just FYI a reason I thought it would be useful to keep a running list of those with the project is for the record keeping reasons (billing and completed tasks) that Israel mentioned but also to append them in some way to the monthly billing statement would help the PIs and research staff have a better idea of what and how often they are requesting support (If I see that I requested labor or skilled staff help 10 times during the month, I should be less surprised by the bill for labor).

**Comment by jSylvestre** [comment]
Also need to generate emails when things happen (Created, taskMessage added, completed)

**Comment by jSylvestre** [comment]
This is pretty much done except for the save without notify.
We can revisit if there are issues.
