### ISSUE TITLE
Service to transfer money via sloth

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#23]
Need to be able to send arbitrary transactions to sloth, ex $X from accountA to accountB and $Y to accountC to accountD. 

We also don't have any backing db structure for tracking charges -- we can do that in a separate issue/sprint but if you have some ideas I'd say just lay something down which will allow us to keep track of all the IDs and links between the two systems.

**Comment by sprucely** [comment]
Closed with PR #48
