### ISSUE TITLE
You can save a quote without entering a field.

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Harvest#234]

**Comment by srkirkland** [comment]
@jSylvestre I'm not sure this is a problem -- you can have a 0 acre project so i would assume this would mean no fields as well.

**Comment by jSylvestre** [comment]
@srkirkland Changing accounts with no fields causes problems:
Just wrap this in a if I think:
https://github.com/ucdavis/Harvest/blob/main/Harvest.Web/Controllers/Api/RequestController.cs#L86

**Comment by srkirkland** [comment]
ok, i'll think i'll be better to just initialize to an empty array in the ctor but i'll try both out
