### ISSUE TITLE
Email service -- Send emails via SMTP

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#25]
want to be able to send emails similar to peaks, except for now we don't have to make a job, we'll just assume all emails are sent real-time.  Test method should be able to send an email reading the contents from a template cshtml page.

**Comment by jSylvestre** [comment]
@srkirkland Couple questions:
1) Will we need to setup an email box, like we did for anlab?
2) If we send realtime, there isn't a good recovery method or way to debug/investigate issues, maybe we should create a simple table with contents, even if we send right away and don't use a job, at least we would have something to checkout if there were problems.

**Comment by srkirkland** [comment]
@jSylvestre I'd like to use our notify.ucdavis.edu domain that we setup for these smaller apps and see how that works.  

For the notifications we might need a table/job eventually but i am not sure it is worth the time at this stage, i would just send away. we can always check sparkpost logs for the basics

**Comment by jSylvestre** [comment]
https://github.com/ucdavis/Harvest/compare/bae14b17ad6a...78dd7deb0fb7
