### ISSUE TITLE
Hide section if it doesn't have anything? (Invoice)

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Harvest#279]
![image](https://user-images.githubusercontent.com/469010/124631587-62ad6e00-de38-11eb-9d90-8f8b2b0402a1.png)

**Comment by jSylvestre** [comment]
Issue #221 But when it is done there, make sure it is the same on the PDF

**Comment by jSylvestre** [comment]
Issue #211 Is the same, just make sure it updates the PDF too.

**Comment by srkirkland** [comment]
gonna keep it
