### ISSUE TITLE
Add in jquery + validation

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#30]
Add jquery and validation into pages that need it.  Probably worth just making as a partial import file since many pages will not need it, but any CSHTML pages with a form will.  Also CSHTML pages with datatables will also need some version of jquery, and they might as well all use the same one.

For reference, a new MVC project from template uses these libs: https://github.com/dotnet/aspnetcore/tree/main/src/ProjectTemplates/Web.ProjectTemplates/content/StarterWeb-CSharp/wwwroot/lib.

Let's at least load the same versions from CDN, but perhaps at some point we'll want to serve the actual files locally as well for development.

**Comment by jSylvestre** [comment]
https://docs.microsoft.com/en-us/aspnet/ajax/cdn/jquery-validate/
