### ISSUE TITLE
Ability to download files

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#331]
- [x] Download from project page
- [x] Download ticket attachments

Download code should already be mostly written in the fileController, but you'll need to augment it to take in the file name.  It'll return a SAS URL which the client should use to download.  to save on network requests, you might want to add another method as well that gets the read SAS URL for multiple files at once.

**Comment by jSylvestre** [comment]
(and sorry for my ugly attachments list for tickets...)
