### ISSUE TITLE
Empty state for project list

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#349]

**Comment by cydoval** [comment]
How should i do this @srkirkland code wise, is there a place where I can add html for an emptystate

**Comment by jSylvestre** [comment]
In here:
https://github.com/ucdavis/Harvest/blob/main/Harvest.Web/ClientApp/src/Projects/ProjectListContainer.tsx#L43
maybe do something like 
`      {projects.length > 0 ? ( 
      <ProjectTable projects={projects}></ProjectTable>) : (<div>Nothing to see</div>)}`

**Comment by srkirkland** [comment]
Assigning to @wongband.  Just add an empty state with a nice bootstrap info alert saying something like `No projects found`
