### ISSUE TITLE
Home dynamic options

### ISSUE THREAD

**Issue by cydoval** [ucdavis/Harvest#351]
Worker: quick actions - enter expenses, view project, add expense to last project/project 1,2,3

**Comment by cydoval** [comment]
PI: quick actions - View My Projects, Request a new Project

**Comment by cydoval** [comment]
Supervisor: quick actions - Enter Expenses, View Projects, Show me most recent saved quote draft

**Comment by cydoval** [comment]
Farm Manager: Quick actions - View unquoted project (take me to projects with status sorted requested at top), Enter expense, view projects, show me recent saved quote draft, recent unapproved project needs attn

**Comment by srkirkland** [comment]
- [ ] Worker
- [ ] PI
- [ ] Supervisor
- [ ] FM
