### ISSUE TITLE
Emails in all the right place

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#359]
- [x] Project creation -- send confirm to PI and FMs
- [x] Ticket create
- [x] Ticket reply
- [x] PI and FMs gets email when quote submitted
- [x] PI and FMs get email when quote approved

**Comment by jSylvestre** [comment]
@srkirkland For quotes, are you sure you want both notified?
I think notify PI when quote submitted, and FM when approved.

**Comment by srkirkland** [comment]
@jSylvestre I think your idea would be fine, I was just figuring that people like to get confirmations of stuff.
