### ISSUE TITLE
KFS Service

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#36]
Want the ability to lookup/validate KFS accounts, and also find out the account manager of a given account.

Will be used for validation when a professor enters accounts to charge, but also in some cases the account manager will need to approve the use of an account for charges so we'll want to grab their user info, create a user account if needed, and then attach some sort of gated page to that.

**Comment by jSylvestre** [comment]
@srkirkland Would this be any income account like what payments does, or will there be special rules like registration (has to belong to CAES org structure)

**Comment by srkirkland** [comment]
IDK, but I'm guessing it'll be a lot more varied because research is often cross-dept.  But as far as this service goes it shouldn't concern itself with any restrictions

**Comment by jSylvestre** [comment]
Oh, because we are taking money out... need more coffee
