### ISSUE TITLE
Files can't be downloaded after being uploaded

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#386]
low priority but when i'm on the project details page and I upload a file, it shows up in the list but you can't download it.  If there was an existing file you can download that one and you are left with one downloadable and one not.  A page refresh makes the file downloadable again.

**Comment by jSylvestre** [comment]
This was happening to me locally, but not when I tried it on the azure site.
I wonder if this happens with larger files/slow upload speed?

**Comment by srkirkland** [comment]
Not sure but let’s update the azure site and try again, maybe it’s because of more recent code.
________________________________

**Comment by jSylvestre** [comment]
I Uploaded 3 files, first and last are clickable, middle one isn't:
![image](https://user-images.githubusercontent.com/469010/128076592-6e8e0318-2ad2-44cc-9e46-1cb1bce3f694.png)
![image](https://user-images.githubusercontent.com/469010/128076602-a6d0c05e-3bbc-4de2-b290-608a6790c619.png)

**Comment by srkirkland** [comment]
@wongband Ok, figured it out and Jason was right, it seems to happen with larger files.  Try uploading something that's a few MB, like a large picture or a big PDF.  I think what is happening is that the file is loaded with a link while it is still uploading, and then when uploading is finished the file info is reset and the link disappears.  If you have trouble reproducing it let me know, I can reproduce it just about every time now.

**Comment by wongband** [comment]
@srkirkland Okay I will try it out
