### ISSUE TITLE
Project date sorting

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Harvest#437]
Isn't sorting by date, just alphabetical

**Comment by srkirkland** [comment]
What you want to do here is have the raw date be the `accessor` and then make a custom render function to show the local date only.  So for example, for the projects table you'd want the end date column to look like this:
```
      {
        id: "endDate",
        Header: "End",
        accessor: "end",
        Cell: (data: Cell<Project>) =>
          new Date(data.value).toLocaleDateString(),
      },
```

You'll have to go through any table we have for any date column this is the way to go.
