### ISSUE TITLE
Big Requirements?

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Harvest#499]
If the requirements have a lot of text it takes up a lot of space everywhere.  If it's longer than 256 characters, truncate with an `...` ellipsis and add a `View More` button.  This button when clicked would open a large modal which shows all of the requirements text, even if it's ver long.

![image](https://user-images.githubusercontent.com/469010/132038878-eaf935ee-ba73-4e4d-a784-503bf241b53e.png)

**Comment by srkirkland** [comment]
Good point, perhaps we can put a collapse (https://reactstrap.github.io/components/collapse/) if the text is more than N characters.  and clicking on the `[See More]` would expand it.

**Comment by sprucely** [comment]
Another option could be to have `[See More]` open a Modal with the full content. I think Modal handles window scrolling for excessive content, or perhaps explicitly add a scrollable view in it.
