### ISSUE TITLE
RazorLight issues

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Harvest#50]
PR #49 Shows the errors trying to run this.

**Comment by sprucely** [comment]
Some good info on doing this with built-in Razor engine
https://www.codemag.com/article/1312081/Rendering-ASP.NET-MVC-Razor-Views-to-String

**Comment by sprucely** [comment]
Went a slightly different route than above comment. Commit eaff297 removes dependency on RazorLight and instead makes use of a "Razor Library" csproj, which can be used from anywhere, including console/job apps.
