### ISSUE TITLE
Make filtering work for date columns

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#517]
use custom filter function or build a custom filter, or possibly just change the accessor but we'll need to make sure sorting still works correctly in all cases.  if we want to get fancy we can make a custom filter of a datepicker which can select a range or single date and we filter to those.

**Comment by jSylvestre** [comment]
Not saying this is a good solution, but it does work:
```
      {
        id: "startDate",
        Header: "Start",
          accessor: (row) => `${row.start} ${new Date(row.start).toLocaleDateString()}`,
        Cell: (data: Cell<Project>) =>
          new Date(data.row.original.start).toLocaleDateString(),
      },
```

**Comment by jSylvestre** [comment]
Possible use a date picker and do something like this:
https://codesandbox.io/s/r40ovqp5jq
