### ISSUE TITLE
Populate Crops.tsx from DB

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Harvest#538]
Currently the crops on the request page are populated from a hard coded array.
Use database crops instead

**Comment by sprucely** [comment]
@jSylvestre Should it just populate the list with everything of the given crop type, or do a search as the user types?

**Comment by jSylvestre** [comment]
@sprucely Scott said just populate it with everything. Or at least, don't do it with a search api.

**Comment by sprucely** [comment]
closed via pr #544
