### ISSUE TITLE
CRUD page to enter values for pricing

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#55]
need pricing information for anything that will go in the quote.  

4 rate types: Acreage, Labor, Equipment and Other.
Each row has type, description, rate, and possibly account info (at least add a field for account number for now).  Also add general fields like createdOn and createdBy, perhaps if you want to get fancy a "effectiveOn" column if we would like to be able to plan ahead for future rates.

See file in https://trello.com/c/DbKKQ4Ci/4-combined-invoice-and-quote-template-our-form-will-likely-follow-closely for examples and structure (rate data tab).

**Comment by jSylvestre** [comment]
So... Assuming my table structure is good.
1) Should update be able to update the price if it is used somewhere?
2) Should Delete actually delete it if it isn't used, or just set the isActive flag always?

**Comment by jSylvestre** [comment]
What do we do with:
maps to PLS acreage fee account (row/tree/EH/WS)

**Comment by jSylvestre** [comment]
@srkirkland Do you want a field for (Hourly, Daily, Per Acre, Per Gallon, etc?)

**Comment by srkirkland** [comment]
@jSylvestre sure you can call it `unit`
