### ISSUE TITLE
PI Search box

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#573]
IF PI selected, disable input. Allow clicking clear button which should re-enable.

Hint text and custom search text saying search by email or kerb.

**Comment by sprucely** [comment]
Just noticed that this was reassigned. The Typeahead control doesn't even display the [clear] button when the control is disabled. Not sure what the best approach would be. Maybe for now just place a [clear] button next to the Typeahead and later see if @cydoval can do some overlay magic with it?
