### ISSUE TITLE
Redo Accounting for Rates and Invoices

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#579]
Rate table accounts need to require CHART, ACCOUNT, and OBJECT CODE, with an optional SUBACCT.  We should use the regular FAU format [insert format here].  NOTE that in a few years the format will be different because of aggie enterprise, so we should remain flexible in the account format.

INVOICE CHANGES:
Invoice charges need to be split based on FAU/Account.  So the process should be similar to this:

- [x] Group all expenses based on FAU, so different account/object/subacct would cause different groups. Since FAU will be just the account field, this shouldn't be too hard.
- [x] For each group of non-passthrough expenses, distribute expenses as before based on account split using object code `3900`
- [x] For each group of `IsPassthrough` charges, distribute object code `3918`
- [x] Add IsPassThrough to the expense table as well (we save the accounted used there to flatten it out) -JS
Add the object code info to config settings since they'll likely change. pr #585

**Comment by jSylvestre** [comment]
May need clarification:
1) Project account require Object code?
2) Rate object code is only determined by if it is a passthrough account? Or does each rate account also require a non-config object code?
3) If a passthrough account is detected, this will require a percentage split (TBD). So each isPassthrough account will need bioth debit and credit splits? (Credit is where the money is going to, debit is from the PI's account(s) )
