### ISSUE TITLE
Page listing all open help tickets.

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Harvest#636]
Limit to Field manager, maybe supervisor?

**Comment by sprucely** [comment]
@jSylvestre Can this one be closed?

**Comment by jSylvestre** [comment]
@sprucely I don't think we have this. But maybe change to a question and or V2?

**Comment by jSylvestre** [comment]
Maybe we do? 
https://harvest-test.azurewebsites.net/ticket/mine
