### ISSUE TITLE
Rate values & updating

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#64]
Proposal:
Rates should never be allowed to change so that we can keep a historical record -- if the value of a rate is updated, we should duplicate the row and then set the old one inactive.  This way we will not only have a good history but expenses can be linked with a FK relationship to the rate and it will always be correct.

**Comment by jSylvestre** [comment]
@srkirkland We may have to allow them to edit deactivated ones if they change the rate, then need to go in after and change the account.

**Comment by srkirkland** [comment]
I don't think we should support allowing changing rates on deactivated ones, but updating historical accounts is a somewhat interesting proposition.  Still not sure we should allow that though.

**Comment by jSylvestre** [comment]
Might not have been clear before:
If we are using the deactivated rate for billing, but the account on that rate record is no longer valid, then me may need a way to change that. 
But this may never happen, so if we need to it could just be something me do manually for them.
