### ISSUE TITLE
Job to manage invoices

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#73]
Job which will run daily and:

1  - create invoices for all active projects on the 1st of the month.  Double check to make sure there isn't a recent (<28 days) invoice already created for that project before creating.  Should include all expenses for that project which aren't associated with another invoice, plus some proration of acreage fees (method TBD).  Use a service to handle making invoices.

2 - finds invoices that haven't been paid and sends them to Sloth to be moved

3 - asks sloth for payment status and updates invoice until it is in the completed state.

**Comment by jSylvestre** [comment]
Add a status to the invoice?

**Comment by srkirkland** [comment]
Depending on the steps that sloth allows.  We'll definitely need to know if an invoice is paid or not so we know if it needs to be sent to sloth.  If sloth has additional info (like accepted, batched, moved in kfs) then it would be good to communicate those back.

**Comment by jSylvestre** [comment]
Any issue with having more than 1 invoice in a month for a project?
I can see creating them as long as there are billable expenses regardless of the number of unprocessed invoices

**Comment by jSylvestre** [comment]
Done, but forgot to reference the issue
