### ISSUE TITLE
ad-hoc Invoices

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Harvest#751]
Looks like they want to be able to create adhoc invoices.
Accounts from the project wouldn't be the same for these.

Maybe have the enter expense allow an account override? Only if FM role and/or if we set a flag on the project?

**Comment by jSylvestre** [comment]
So, don't do it with the expense.
Instead, let them enter expenses normally.
In the unbilled expenses page, have a "create special invoice" button and page that lets them create an invoice right away and for them to specify an account (maybe multiple)

When we process these special invoices, instead of using the account(s) on the project, use the account attached to the invoice.

**Comment by jSylvestre** [comment]
Maybe have a flag on the project indicating that this is a special one where invoiced are *only* created manually.

**Comment by srkirkland** [comment]
Make a "direct expenses" page which creates an immediately creates and completes a shell project w/ empty quote.

**Comment by srkirkland** [comment]
we have adhoc now
