### ISSUE TITLE
18 day auto closeout

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Harvest#761]
If awaiting closeout for that long, just auto-close

**Comment by jSylvestre** [comment]
Don't have to worry about logs or writing who did it.
But we probably want to fire off and email saying it was auto closed.
Job just has to call similar code:
`        
[HttpPost]
        [Authorize(Policy = AccessCodes.PrincipalInvestigator)]
        public async Task<ActionResult> DoCloseout(int projectId)
        {
            var result = await _invoiceService.CreateInvoice(projectId, true);
            return Ok(result);
        }
`
